create table public.waitlist_subscribers (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  status text not null default 'pending'
    check (status in ('pending', 'confirmed', 'unsubscribed')),
  confirmation_token_hash text not null unique
    check (char_length(confirmation_token_hash) = 64),
  unsubscribe_token_hash text not null unique
    check (char_length(unsubscribe_token_hash) = 64),
  consent_version text not null,
  consent_at timestamptz not null default now(),
  confirmation_sent_at timestamptz,
  confirmed_at timestamptz,
  unsubscribed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint waitlist_email_normalized check (email = lower(btrim(email)))
);

create table public.waitlist_email_log (
  id bigint generated by default as identity primary key,
  subscriber_id uuid not null references public.waitlist_subscribers(id) on delete cascade,
  kind text not null check (kind in ('confirmation', 'launch_reminder')),
  sent_at timestamptz not null default now()
);

create index waitlist_subscribers_status_idx
  on public.waitlist_subscribers (status);

create index waitlist_email_log_sent_at_idx
  on public.waitlist_email_log (sent_at desc);

alter table public.waitlist_subscribers enable row level security;
alter table public.waitlist_email_log enable row level security;

revoke all on table public.waitlist_subscribers from anon, authenticated;
revoke all on table public.waitlist_email_log from anon, authenticated;
revoke all on sequence public.waitlist_email_log_id_seq from anon, authenticated;

comment on table public.waitlist_subscribers is
  'Double-opt-in reminder list. Accessible only through trusted server-side code.';

comment on table public.waitlist_email_log is
  'Minimal delivery log used for cooldown and daily sending limits.';
